/*
  
   Multicore 2 / Multicore 2+
  
   Copyright (c) 2017-2020 - Victor Trucco

  
   All rights reserved
  
   Redistribution and use in source and synthezised forms, with or without
   modification, are permitted provided that the following conditions are met:
  
   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
  
   Redistributions in synthesized form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
  
   Neither the name of the author nor the names of other contributors may
   be used to endorse or promote products derived from this software without
   specific prior written permission.
  
   THIS CODE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
   THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
   PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE
   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
   POSSIBILITY OF SUCH DAMAGE.
  
   You are responsible for any legal issues arising from your use of this code.
  
*/// ------------------------------ usbHostSlaveReg_define.v ----------------------------
`include "wishBoneBus_h.v"
`include "usbHostSlave_h.v"



`define RA_EP0_CONTROL_REG              `SCREG_BASE+`ENDPOINT_CONTROL_REG
`define RA_EP0_STATUS_REG               `SCREG_BASE+`ENDPOINT_STATUS_REG
`define RA_EP0_TRANSTYPE_STATUS_REG     `SCREG_BASE+`ENDPOINT_TRANSTYPE_STATUS_REG
`define RA_EP0_NAK_TRANSTYPE_STATUS_REG `SCREG_BASE+`NAK_TRANSTYPE_STATUS_REG
`define RA_EP1_CONTROL_REG              `SCREG_BASE+`NUM_OF_REGISTERS_PER_ENDPOINT+`ENDPOINT_CONTROL_REG
`define RA_EP1_STATUS_REG               `SCREG_BASE+`NUM_OF_REGISTERS_PER_ENDPOINT+`ENDPOINT_STATUS_REG
`define RA_EP1_TRANSTYPE_STATUS_REG     `SCREG_BASE+`NUM_OF_REGISTERS_PER_ENDPOINT+`ENDPOINT_TRANSTYPE_STATUS_REG
`define RA_EP1_NAK_TRANSTYPE_STATUS_REG `SCREG_BASE+`NUM_OF_REGISTERS_PER_ENDPOINT+`NAK_TRANSTYPE_STATUS_REG
`define RA_EP2_CONTROL_REG              `SCREG_BASE+(`NUM_OF_REGISTERS_PER_ENDPOINT*2)+`ENDPOINT_CONTROL_REG
`define RA_EP2_STATUS_REG               `SCREG_BASE+(`NUM_OF_REGISTERS_PER_ENDPOINT*2)+`ENDPOINT_STATUS_REG
`define RA_EP2_TRANSTYPE_STATUS_REG     `SCREG_BASE+(`NUM_OF_REGISTERS_PER_ENDPOINT*2)`+`ENDPOINT_TRANSTYPE_STATUS_REG
`define RA_EP2_NAK_TRANSTYPE_STATUS_REG `SCREG_BASE+(`NUM_OF_REGISTERS_PER_ENDPOINT*2)+`NAK_TRANSTYPE_STATUS_REG
`define RA_EP3_CONTROL_REG              `SCREG_BASE+(`NUM_OF_REGISTERS_PER_ENDPOINT*3)+`ENDPOINT_CONTROL_REG
`define RA_EP3_STATUS_REG               `SCREG_BASE+(`NUM_OF_REGISTERS_PER_ENDPOINT*3)+`ENDPOINT_STATUS_REG
`define RA_EP3_TRANSTYPE_STATUS_REG     `SCREG_BASE+(NUM_OF_REGISTERS_PER_ENDPOINT*3)+`ENDPOINT_TRANSTYPE_STATUS_REG
`define RA_EP3_NAK_TRANSTYPE_STATUS_REG `SCREG_BASE+(`NUM_OF_REGISTERS_PER_ENDPOINT*3)+`NAK_TRANSTYPE_STATUS_REG
`define RA_SC_CONTROL_REG               `SCREG_BASE+`SC_CONTROL_REG
`define RA_SC_LINE_STATUS_REG           `SCREG_BASE+`SC_LINE_STATUS_REG
`define RA_SC_INTERRUPT_STATUS_REG      `SCREG_BASE+`SC_INTERRUPT_STATUS_REG
`define RA_SC_INTERRUPT_MASK_REG        `SCREG_BASE+`SC_INTERRUPT_MASK_REG
`define RA_SC_ADDRESS                   `SCREG_BASE+`SC_ADDRESS
`define RA_SC_FRAME_NUM_MSP             `SCREG_BASE+`SC_FRAME_NUM_MSP
`define RA_SC_FRAME_NUM_LSP             `SCREG_BASE+`SC_FRAME_NUM_LSP

`define RA_EP0_RX_FIFO_DATA_REG         `EP0_RX_FIFO_BASE+`FIFO_DATA_REG
`define RA_EP0_RX_FIFO_STATUS_REG       `EP0_RX_FIFO_BASE+`FIFO_STATUS_REG
`define RA_EP0_RX_FIFO_DATA_COUNT_MSB   `EP0_RX_FIFO_BASE+`FIFO_DATA_COUNT_MSB
`define RA_EP0_RX_FIFO_DATA_COUNT_LSB   `EP0_RX_FIFO_BASE+`FIFO_DATA_COUNT_LSB
`define RA_EP0_RX_FIFO_CONTROL_REG      `EP0_RX_FIFO_BASE+`FIFO_CONTROL_REG
`define RA_EP0_TX_FIFO_DATA_REG         `EP0_TX_FIFO_BASE+`FIFO_DATA_REG
`define RA_EP0_TX_FIFO_STATUS_REG       `EP0_TX_FIFO_BASE+`FIFO_STATUS_REG
`define RA_EP0_TX_FIFO_DATA_COUNT_MSB   `EP0_TX_FIFO_BASE+`FIFO_DATA_COUNT_MSB
`define RA_EP0_TX_FIFO_DATA_COUNT_LSB   `EP0_TX_FIFO_BASE+`FIFO_DATA_COUNT_LSB
`define RA_EP0_TX_FIFO_CONTROL_REG      `EP0_TX_FIFO_BASE+`FIFO_CONTROL_REG

`define RA_EP1_RX_FIFO_DATA_REG         `EP1_RX_FIFO_BASE+`FIFO_DATA_REG
`define RA_EP1_RX_FIFO_STATUS_REG       `EP1_RX_FIFO_BASE+`FIFO_STATUS_REG
`define RA_EP1_RX_FIFO_DATA_COUNT_MSB   `EP1_RX_FIFO_BASE+`FIFO_DATA_COUNT_MSB
`define RA_EP1_RX_FIFO_DATA_COUNT_LSB   `EP1_RX_FIFO_BASE+`FIFO_DATA_COUNT_LSB
`define RA_EP1_RX_FIFO_CONTROL_REG      `EP1_RX_FIFO_BASE+`FIFO_CONTROL_REG
`define RA_EP1_TX_FIFO_DATA_REG         `EP1_TX_FIFO_BASE+`FIFO_DATA_REG
`define RA_EP1_TX_FIFO_STATUS_REG       `EP1_TX_FIFO_BASE+`FIFO_STATUS_REG
`define RA_EP1_TX_FIFO_DATA_COUNT_MSB   `EP1_TX_FIFO_BASE+`FIFO_DATA_COUNT_MSB
`define RA_EP1_TX_FIFO_DATA_COUNT_LSB   `EP1_TX_FIFO_BASE+`FIFO_DATA_COUNT_LSB
`define RA_EP1_TX_FIFO_CONTROL_REG      `EP1_TX_FIFO_BASE+`FIFO_CONTROL_REG

`define RA_EP2_RX_FIFO_DATA_REG         `EP2_RX_FIFO_BASE+`FIFO_DATA_REG
`define RA_EP2_RX_FIFO_STATUS_REG       `EP2_RX_FIFO_BASE+`FIFO_STATUS_REG
`define RA_EP2_RX_FIFO_DATA_COUNT_MSB   `EP2_RX_FIFO_BASE+`FIFO_DATA_COUNT_MSB
`define RA_EP2_RX_FIFO_DATA_COUNT_LSB   `EP2_RX_FIFO_BASE+`FIFO_DATA_COUNT_LSB
`define RA_EP2_RX_FIFO_CONTROL_REG      `EP2_RX_FIFO_BASE+`FIFO_CONTROL_REG
`define RA_EP2_TX_FIFO_DATA_REG         `EP2_TX_FIFO_BASE+`FIFO_DATA_REG
`define RA_EP2_TX_FIFO_STATUS_REG       `EP2_TX_FIFO_BASE+`FIFO_STATUS_REG
`define RA_EP2_TX_FIFO_DATA_COUNT_MSB   `EP2_TX_FIFO_BASE+`FIFO_DATA_COUNT_MSB
`define RA_EP2_TX_FIFO_DATA_COUNT_LSB   `EP2_TX_FIFO_BASE+`FIFO_DATA_COUNT_LSB
`define RA_EP2_TX_FIFO_CONTROL_REG      `EP2_TX_FIFO_BASE+`FIFO_CONTROL_REG

`define RA_EP3_RX_FIFO_DATA_REG         `EP3_RX_FIFO_BASE+`FIFO_DATA_REG
`define RA_EP3_RX_FIFO_STATUS_REG       `EP3_RX_FIFO_BASE+`FIFO_STATUS_REG
`define RA_EP3_RX_FIFO_DATA_COUNT_MSB   `EP3_RX_FIFO_BASE+`FIFO_DATA_COUNT_MSB
`define RA_EP3_RX_FIFO_DATA_COUNT_LSB   `EP3_RX_FIFO_BASE+`FIFO_DATA_COUNT_LSB
`define RA_EP3_RX_FIFO_CONTROL_REG      `EP3_RX_FIFO_BASE+`FIFO_CONTROL_REG
`define RA_EP3_TX_FIFO_DATA_REG         `EP3_TX_FIFO_BASE+`FIFO_DATA_REG
`define RA_EP3_TX_FIFO_STATUS_REG       `EP3_TX_FIFO_BASE+`FIFO_STATUS_REG
`define RA_EP3_TX_FIFO_DATA_COUNT_MSB   `EP3_TX_FIFO_BASE+`FIFO_DATA_COUNT_MSB
`define RA_EP3_TX_FIFO_DATA_COUNT_LSB   `EP3_TX_FIFO_BASE+`FIFO_DATA_COUNT_LSB
`define RA_EP3_TX_FIFO_CONTROL_REG      `EP3_TX_FIFO_BASE+`FIFO_CONTROL_REG

`define RA_HOST_SLAVE_MODE              `HOST_SLAVE_CONTROL_BASE+`HOST_SLAVE_CONTROL_REG
`define RA_HOST_SLAVE_VERSION           `HOST_SLAVE_CONTROL_BASE+`HOST_SLAVE_VERSION_REG


